### ISSUE TITLE
[1 XP] Setup a React app - [GROUP - Front-end]

### ISSUE THREAD

**Issue by petushka1** [Theophileaseh/Doctor-Appointment-Back-end#11]
**setup repo with:**
- [ ] Linters
- [ ] Jest
- [ ] Redux (set up routing)
- [ ] create the main structure
- [ ] add Bootstrap
- [ ] add Fonts

**Comment by Theophileaseh** [comment]
Fixes https://github.com/c3c1l1a/Doctors-Appointment-Front-End/pull/1
